homepage:
    path:     index
    defaults:
        _controller: AppBundle:Default:index

room_home:
    path:     room
    defaults:
        _controller: AppBundle:Room:index

room_home_add:
    path:     room/add
    defaults:
        _controller: AppBundle:Room:add

room_home_delete:
    path:     room/delete/{id}
    defaults:
        _controller: AppBundle:Room:delete


equipment_home:
    path:     equipment
    defaults:
        _controller: AppBundle:Equipment:index

equipment_home_delete:
    path:     equipment/delete/{id}
    defaults:
        _controller: AppBundle:Equipment:delete


category_home:
    path:     category
    defaults:
        _controller: AppBundle:Category:index

category_home_add:
    path:     category/add
    defaults:
        _controller: AppBundle:Category:new

category_home_delete:
    path:     category/delete/{id}
    defaults:
        _controller: AppBundle:Category:delete

category_home_edit:
    path:     category/edit/{id}
    defaults:
        _controller: AppBundle:Category:edit


code_home:
    path:     codebarre
    defaults:
        _controller: AppBundle:BarCode:index

code_home_add:
    path:     equipment/add
    defaults:
        _controller: AppBundle:BarCode:add